# Generated by Django 5.0.4 on 2024-05-05 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obrazki', '0002_remove_obrazek_autor_obrazek_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObrazekTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='obrazek',
            name='svg_obraz',
        ),
        migrations.AddField(
            model_name='obrazek',
            name='data_publikacji',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='obrazek',
            name='opis',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='obrazek',
            name='tags',
            field=models.ManyToManyField(to='obrazki.obrazektag'),
        ),
    ]
